/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.legourmet.view;

import br.com.legourmet.dao.UsuarioDAO;
import br.com.legourmet.model.Usuario;
import java.util.Calendar;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import org.apache.commons.codec.digest.DigestUtils;

/**
 *
 * @author gouri
 */
public class FormNovoUsuario extends javax.swing.JFrame {

    /**
     * Creates new form FormNovoItem
     */
    public FormNovoUsuario() {
        initComponents();
        selecionarPerfil();
        this.setResizable(false);
        this.setLocationRelativeTo(null);//Tela centralizada
    }

    private void selecionarPerfil() {
        choicePerfil3.addItem("Administrador");
        choicePerfil3.addItem("Caixa");
        choicePerfil3.addItem("Cozinha");
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bgSituacao3 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        btnFechar3 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        choicePerfil3 = new java.awt.Choice();
        jLabel20 = new javax.swing.JLabel();
        txtNome3 = new javax.swing.JTextField();
        jLabel22 = new javax.swing.JLabel();
        jrbAtivo3 = new javax.swing.JRadioButton();
        jrbBloqueado3 = new javax.swing.JRadioButton();
        btnSalvar2 = new java.awt.Button();
        btnCancelar3 = new java.awt.Button();
        btnLimpar2 = new java.awt.Button();
        jLabel2 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        txtLogin3 = new javax.swing.JTextField();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        txtConfirmarSenha3 = new javax.swing.JPasswordField();
        txtSenha3 = new javax.swing.JPasswordField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(24, 34, 56));

        jPanel2.setBackground(new java.awt.Color(239, 152, 43));
        jPanel2.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                jPanel2MouseDragged(evt);
            }
        });
        jPanel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jPanel2MousePressed(evt);
            }
        });

        btnFechar3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/legourmet/imgs/icons8_Close_Window_25px_2.png"))); // NOI18N
        btnFechar3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnFechar3MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnFechar3)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnFechar3, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
        );

        jLabel3.setForeground(new java.awt.Color(102, 102, 102));
        jLabel3.setText("Perfil");

        choicePerfil3.setBackground(new java.awt.Color(238, 230, 199));
        choicePerfil3.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        choicePerfil3.setForeground(new java.awt.Color(24, 34, 56));

        jLabel20.setForeground(new java.awt.Color(102, 102, 102));
        jLabel20.setText("Nome");

        txtNome3.setBackground(new java.awt.Color(238, 230, 199));
        txtNome3.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        txtNome3.setForeground(new java.awt.Color(24, 34, 56));
        txtNome3.setBorder(null);
        txtNome3.setCaretColor(new java.awt.Color(24, 34, 56));
        txtNome3.setPreferredSize(new java.awt.Dimension(2, 20));
        txtNome3.setSelectionColor(new java.awt.Color(239, 152, 43));

        jLabel22.setForeground(new java.awt.Color(102, 102, 102));
        jLabel22.setText("Situação");

        jrbAtivo3.setBackground(new java.awt.Color(24, 34, 56));
        bgSituacao3.add(jrbAtivo3);
        jrbAtivo3.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        jrbAtivo3.setForeground(new java.awt.Color(255, 255, 255));
        jrbAtivo3.setSelected(true);
        jrbAtivo3.setText("Ativo");

        jrbBloqueado3.setBackground(new java.awt.Color(24, 34, 56));
        bgSituacao3.add(jrbBloqueado3);
        jrbBloqueado3.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        jrbBloqueado3.setForeground(new java.awt.Color(255, 255, 255));
        jrbBloqueado3.setText("Bloqueado");

        btnSalvar2.setBackground(new java.awt.Color(239, 152, 43));
        btnSalvar2.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        btnSalvar2.setForeground(new java.awt.Color(24, 34, 56));
        btnSalvar2.setLabel("SALVAR");
        btnSalvar2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalvar2ActionPerformed(evt);
            }
        });

        btnCancelar3.setBackground(new java.awt.Color(239, 152, 43));
        btnCancelar3.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        btnCancelar3.setForeground(new java.awt.Color(24, 34, 56));
        btnCancelar3.setLabel("CANCELAR");
        btnCancelar3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelar3ActionPerformed(evt);
            }
        });

        btnLimpar2.setBackground(new java.awt.Color(239, 152, 43));
        btnLimpar2.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        btnLimpar2.setForeground(new java.awt.Color(24, 34, 56));
        btnLimpar2.setLabel("LIMPAR");
        btnLimpar2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimpar2ActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(102, 102, 102));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Novo Usuário");

        jLabel23.setForeground(new java.awt.Color(102, 102, 102));
        jLabel23.setText("Login");

        txtLogin3.setBackground(new java.awt.Color(238, 230, 199));
        txtLogin3.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        txtLogin3.setForeground(new java.awt.Color(24, 34, 56));
        txtLogin3.setBorder(null);
        txtLogin3.setCaretColor(new java.awt.Color(24, 34, 56));
        txtLogin3.setPreferredSize(new java.awt.Dimension(2, 20));
        txtLogin3.setSelectionColor(new java.awt.Color(239, 152, 43));

        jLabel24.setForeground(new java.awt.Color(102, 102, 102));
        jLabel24.setText("Senha");

        jLabel25.setForeground(new java.awt.Color(102, 102, 102));
        jLabel25.setText("Digite a senha novamente");

        txtConfirmarSenha3.setBackground(new java.awt.Color(238, 230, 199));
        txtConfirmarSenha3.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        txtConfirmarSenha3.setForeground(new java.awt.Color(24, 34, 56));
        txtConfirmarSenha3.setBorder(null);
        txtConfirmarSenha3.setCaretColor(new java.awt.Color(24, 34, 56));
        txtConfirmarSenha3.setSelectionColor(new java.awt.Color(239, 152, 43));

        txtSenha3.setBackground(new java.awt.Color(238, 230, 199));
        txtSenha3.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        txtSenha3.setForeground(new java.awt.Color(24, 34, 56));
        txtSenha3.setBorder(null);
        txtSenha3.setCaretColor(new java.awt.Color(24, 34, 56));
        txtSenha3.setSelectionColor(new java.awt.Color(239, 152, 43));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 555, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel25)
                            .addComponent(jLabel24)
                            .addComponent(jLabel23)
                            .addComponent(jLabel3)
                            .addComponent(jLabel20)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jrbAtivo3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jrbBloqueado3))
                            .addComponent(jLabel22)
                            .addComponent(txtNome3, javax.swing.GroupLayout.PREFERRED_SIZE, 227, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(choicePerfil3, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(txtSenha3, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(txtConfirmarSenha3, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(txtLogin3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(164, 164, 164))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(btnSalvar2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnLimpar2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(57, 57, 57)
                        .addComponent(btnCancelar3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(33, 33, 33))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addGap(35, 35, 35)
                .addComponent(jLabel3)
                .addGap(1, 1, 1)
                .addComponent(choicePerfil3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel20)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtNome3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel23)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtLogin3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(13, 13, 13)
                .addComponent(jLabel24)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtSenha3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(17, 17, 17)
                .addComponent(jLabel25)
                .addGap(5, 5, 5)
                .addComponent(txtConfirmarSenha3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel22)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jrbAtivo3)
                    .addComponent(jrbBloqueado3))
                .addGap(24, 24, 24)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnCancelar3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnLimpar2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSalvar2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(42, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 500));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    //Cancela Criação do novo usuário
    private void btnFechar3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnFechar3MouseClicked
        int resposta = JOptionPane.showConfirmDialog(null, "Alterações não serão salvas.\nDeseja Realmente sair?", "Sair", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);
        if (resposta == JOptionPane.YES_OPTION) {
            this.dispose();
        }
    }//GEN-LAST:event_btnFechar3MouseClicked

    private void btnCancelar3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelar3ActionPerformed
        int resposta = JOptionPane.showConfirmDialog(null, "Alterações não serão salvas.\nDeseja Realmente sair?", "Sair", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);
        if (resposta == JOptionPane.YES_OPTION) {
            this.dispose();
        }
    }//GEN-LAST:event_btnCancelar3ActionPerformed

    // Métodos jPanel2MouseDragged e jPanel2MousePressed são para mover a tela
    private void jPanel2MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel2MouseDragged
         // src to drag
        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();
        this.setLocation(x-xx, y-xy);
    }//GEN-LAST:event_jPanel2MouseDragged

    int xx, xy;
    private void jPanel2MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel2MousePressed
        // drag this pane
        xx = evt.getX();
        xy = evt.getY();
    }//GEN-LAST:event_jPanel2MousePressed

    private void btnSalvar2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalvar2ActionPerformed
        Usuario usuario = null;

        if (txtNome3.equals("")) {
            JOptionPane.showMessageDialog(this,
                    "Nome Obrigatório");
            txtNome3.requestFocus();
            return;
        } else if (txtLogin3.equals("")) {
            JOptionPane.showMessageDialog(this,
                    "Login Obrigatório");
            txtLogin3.requestFocus();
            return;
        } else if (txtSenha3.equals("")) {
            JOptionPane.showMessageDialog(this,
                    "Senha Obrigatória");
            txtSenha3.requestFocus();
            return;
        } else if (txtSenha3.equals(txtConfirmarSenha3)) {
            JOptionPane.showMessageDialog(this,
                    "As senhas precisam ser iguais");
            txtSenha3.setText("");
            txtConfirmarSenha3.setText("");
            txtSenha3.requestFocus();
            return;
        }else{
            usuario = new Usuario();
        }
        usuario.setNome(txtNome3.getText());
        usuario.setLogin(txtLogin3.getText());
        String senhaCriptografada = DigestUtils.sha512Hex(txtSenha3.toString());
        usuario.setSenha(senhaCriptografada);
        if(jrbAtivo3.isSelected()){
            usuario.setPerfil(jrbAtivo3.getText());
        }else{
            usuario.setPerfil(jrbBloqueado3.getText());
        }
        
        usuario.setData_UltimoAcesso(Calendar.getInstance());
        
        try {
            UsuarioDAO.inserir(usuario);
            JOptionPane.showMessageDialog(this,
                "Dados salvos com sucesso!");
            dispose();
        } catch (Exception ex) {
            Logger.getLogger(FormNovoUsuario.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(this, ex.getMessage(), "Erro", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnSalvar2ActionPerformed

    private void btnLimpar2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimpar2ActionPerformed
        txtNome3.setText("");
        txtLogin3.setText("");
        txtSenha3.setText("");
        txtConfirmarSenha3.setText("");
        txtNome3.requestFocus();
        return;
    }//GEN-LAST:event_btnLimpar2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Windows look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormNovoUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormNovoUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormNovoUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormNovoUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormNovoUsuario().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup bgSituacao3;
    private java.awt.Button btnCancelar3;
    private javax.swing.JLabel btnFechar3;
    private java.awt.Button btnLimpar2;
    private java.awt.Button btnSalvar2;
    private java.awt.Choice choicePerfil3;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JRadioButton jrbAtivo3;
    private javax.swing.JRadioButton jrbBloqueado3;
    private javax.swing.JPasswordField txtConfirmarSenha3;
    private javax.swing.JTextField txtLogin3;
    private javax.swing.JTextField txtNome3;
    private javax.swing.JPasswordField txtSenha3;
    // End of variables declaration//GEN-END:variables
}
