/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.legourmet.view;

import br.com.legourmet.dao.PagamentoDAO;
import br.com.legourmet.dao.UsuarioDAO;
import br.com.legourmet.model.Pagamento;
import br.com.legourmet.model.PagamentoTableModel;
import br.com.legourmet.model.Usuario;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author gouri
 */
public class FormPagamentos extends javax.swing.JFrame {

    private PagamentoTableModel pagamentoTableModel;

    private void prepararTable() {
        PagamentoDAO pagamentoDAO = new PagamentoDAO();
        ArrayList<Pagamento> pagamentos = new ArrayList<>();
        try {
            pagamentos = pagamentoDAO.listar();
        } catch (Exception ex) {
            Logger.getLogger(FormCardapio.class.getName()).log(Level.SEVERE, null, ex);
        }
        //pesquisar clientes cadastrados no banco de dados
        pagamentoTableModel = new PagamentoTableModel(pagamentos);
        tableListaPagamentos.setModel(pagamentoTableModel);
    }

    /**
     * Creates new form FormPrincipalAdmin
     */
    public FormPagamentos() {
        initComponents();
        this.setResizable(false);
        this.setLocationRelativeTo(null);//Tela centralizada
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bgOpcao1 = new javax.swing.ButtonGroup();
        jPanel2 = new javax.swing.JPanel();
        btnHome2 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableFormaPagamento1 = new javax.swing.JTable();
        jLabel9 = new javax.swing.JLabel();
        btnImprimir1 = new java.awt.Button();
        jScrollPane2 = new javax.swing.JScrollPane();
        tableListaPagamentos = new javax.swing.JTable();
        jLabel4 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jTFTotal1 = new javax.swing.JTextField();
        jPanel4 = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        txtNomeCliente2 = new javax.swing.JTextField();
        btnPesquisarNome = new javax.swing.JLabel();
        btnPesquisa2 = new java.awt.Button();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        choiceDia1 = new java.awt.Choice();
        choiceMes1 = new java.awt.Choice();
        choiceAno1 = new java.awt.Choice();
        jLabel23 = new javax.swing.JLabel();
        jrbDia1 = new javax.swing.JRadioButton();
        jrbMes1 = new javax.swing.JRadioButton();
        jrbAno1 = new javax.swing.JRadioButton();
        jLabel24 = new javax.swing.JLabel();
        btnPesquisarValorTotal = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(239, 152, 43));
        jPanel2.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                jPanel2MouseDragged(evt);
            }
        });
        jPanel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jPanel2MousePressed(evt);
            }
        });

        btnHome2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/legourmet/imgs/icons8_Home_25px.png"))); // NOI18N
        btnHome2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnHome2MousePressed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(1175, Short.MAX_VALUE)
                .addComponent(btnHome2)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnHome2, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1210, 40));

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jScrollPane1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));

        tableFormaPagamento1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        tableFormaPagamento1.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        tableFormaPagamento1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"Cartão",  new Double(200.0)}
            },
            new String [] {
                "Forma de Pagamento", "Valor Pagamento (R$)"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.Double.class
            };
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tableFormaPagamento1.setGridColor(new java.awt.Color(255, 255, 255));
        tableFormaPagamento1.setRowHeight(22);
        tableFormaPagamento1.setSelectionBackground(new java.awt.Color(255, 96, 2));
        jScrollPane1.setViewportView(tableFormaPagamento1);

        jPanel3.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(25, 449, 920, 140));

        jLabel9.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(102, 102, 102));
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setText("Lista de Pagamentos");
        jPanel3.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(34, 20, 900, -1));

        btnImprimir1.setBackground(new java.awt.Color(249, 189, 0));
        btnImprimir1.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        btnImprimir1.setForeground(new java.awt.Color(102, 102, 102));
        btnImprimir1.setLabel("IMPRIMIR RELATÓRIO");
        jPanel3.add(btnImprimir1, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 650, -1, -1));

        jScrollPane2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));

        tableListaPagamentos.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        tableListaPagamentos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"12/09/2018", "pedro.dias", "elvisla",  new Integer(2),  new Integer(4),  new Integer(2),  new Double(200.0)},
                {"10/11/2018", "michele.mello", "fulano",  new Integer(5),  new Integer(3),  new Integer(3),  new Double(100.0)},
                {"11/12/2018", "pedro.dias", "beltrano",  new Integer(10),  new Integer(9),  new Integer(2),  new Double(350.0)},
                {"20/12/2018", "michele.mello", "cicrano",  new Integer(12),  new Integer(11),  new Integer(7),  new Double(180.0)}
            },
            new String [] {
                "Data", "Login Usuário", "Login Cliente", "Código Pedido", "Código do Pagamento", "Qtd. Itens", "Valor Pedido"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.Double.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tableListaPagamentos.setGridColor(new java.awt.Color(255, 255, 255));
        tableListaPagamentos.setSelectionBackground(new java.awt.Color(239, 152, 43));
        jScrollPane2.setViewportView(tableListaPagamentos);

        jPanel3.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 60, 910, 330));

        jLabel4.setForeground(new java.awt.Color(102, 102, 102));
        jLabel4.setText("________________________________________________________________________Mains detalhes ______________________________________________________________________");
        jPanel3.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 410, -1, 20));

        jLabel26.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        jLabel26.setForeground(new java.awt.Color(102, 102, 102));
        jLabel26.setText("Total (R$) :");
        jPanel3.add(jLabel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 630, -1, -1));

        jTFTotal1.setBackground(new java.awt.Color(239, 152, 43));
        jTFTotal1.setForeground(new java.awt.Color(255, 255, 255));
        jTFTotal1.setBorder(null);
        jTFTotal1.setCaretColor(new java.awt.Color(255, 255, 255));
        jTFTotal1.setEnabled(false);
        jTFTotal1.setPreferredSize(new java.awt.Dimension(2, 20));
        jPanel3.add(jTFTotal1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 650, 170, -1));

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 40, 970, 720));

        jPanel4.setBackground(new java.awt.Color(249, 189, 0));

        jLabel14.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(102, 102, 102));
        jLabel14.setText("Nome do cliente");

        txtNomeCliente2.setBackground(new java.awt.Color(239, 152, 43));
        txtNomeCliente2.setForeground(new java.awt.Color(255, 255, 255));
        txtNomeCliente2.setBorder(null);
        txtNomeCliente2.setCaretColor(new java.awt.Color(255, 255, 255));
        txtNomeCliente2.setPreferredSize(new java.awt.Dimension(2, 20));

        btnPesquisarNome.setForeground(new java.awt.Color(102, 102, 102));
        btnPesquisarNome.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/legourmet/imgs/icons8_Search_18px.png"))); // NOI18N
        btnPesquisarNome.setText("Pesquisar");
        btnPesquisarNome.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnPesquisarNome.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnPesquisarNomeMouseClicked(evt);
            }
        });

        btnPesquisa2.setBackground(new java.awt.Color(249, 189, 0));
        btnPesquisa2.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        btnPesquisa2.setForeground(new java.awt.Color(102, 102, 102));
        btnPesquisa2.setLabel("PESQUISAR");
        btnPesquisa2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPesquisa2ActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(102, 102, 102));
        jLabel5.setText("Mês");

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(102, 102, 102));
        jLabel6.setText("Dia");

        jLabel7.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(102, 102, 102));
        jLabel7.setText("Ano");

        choiceDia1.setBackground(new java.awt.Color(239, 152, 43));
        choiceDia1.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        choiceDia1.setForeground(new java.awt.Color(255, 255, 255));
        choiceDia1.setName("Dia"); // NOI18N

        choiceMes1.setBackground(new java.awt.Color(239, 152, 43));
        choiceMes1.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        choiceMes1.setForeground(new java.awt.Color(255, 255, 255));
        choiceMes1.setName("Dia"); // NOI18N

        choiceAno1.setBackground(new java.awt.Color(239, 152, 43));
        choiceAno1.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        choiceAno1.setForeground(new java.awt.Color(255, 255, 255));
        choiceAno1.setName("Dia"); // NOI18N

        jLabel23.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        jLabel23.setForeground(new java.awt.Color(102, 102, 102));
        jLabel23.setText("Valor Total (R$) :");

        jrbDia1.setBackground(new java.awt.Color(249, 189, 0));
        bgOpcao1.add(jrbDia1);
        jrbDia1.setForeground(new java.awt.Color(102, 102, 102));
        jrbDia1.setSelected(true);
        jrbDia1.setText("Dia");

        jrbMes1.setBackground(new java.awt.Color(249, 189, 0));
        bgOpcao1.add(jrbMes1);
        jrbMes1.setForeground(new java.awt.Color(102, 102, 102));
        jrbMes1.setText("Mês");
        jrbMes1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jrbMes1ActionPerformed(evt);
            }
        });

        jrbAno1.setBackground(new java.awt.Color(249, 189, 0));
        bgOpcao1.add(jrbAno1);
        jrbAno1.setForeground(new java.awt.Color(102, 102, 102));
        jrbAno1.setText("Ano");

        jLabel24.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/legourmet/imgs/icons8_Graph_Report_100px.png"))); // NOI18N

        btnPesquisarValorTotal.setForeground(new java.awt.Color(102, 102, 102));
        btnPesquisarValorTotal.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/legourmet/imgs/icons8_Search_18px.png"))); // NOI18N
        btnPesquisarValorTotal.setText("Pesquisar");
        btnPesquisarValorTotal.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnPesquisarValorTotal.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnPesquisarValorTotalMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jrbDia1, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jrbMes1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jrbAno1))
                    .addComponent(jLabel14)
                    .addComponent(btnPesquisa2, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtNomeCliente2, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addComponent(btnPesquisarNome)))
                .addGap(48, 48, 48))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel24)
                .addGap(68, 68, 68))
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(choiceDia1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(choiceMes1, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(choiceAno1, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel7)))
                            .addComponent(jLabel23)))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(82, 82, 82)
                        .addComponent(btnPesquisarValorTotal)))
                .addContainerGap(19, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(2, 2, 2)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(choiceDia1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(choiceMes1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(choiceAno1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(41, 41, 41)
                .addComponent(jLabel23)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jrbDia1)
                    .addComponent(jrbMes1)
                    .addComponent(jrbAno1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnPesquisarValorTotal)
                .addGap(48, 48, 48)
                .addComponent(jLabel14)
                .addGap(1, 1, 1)
                .addComponent(txtNomeCliente2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnPesquisarNome)
                .addGap(39, 39, 39)
                .addComponent(btnPesquisa2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(72, 72, 72)
                .addComponent(jLabel24)
                .addContainerGap(172, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 40, 240, 720));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jrbMes1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jrbMes1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jrbMes1ActionPerformed

    // Volta para FormPrincipal
    private void btnHome2MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnHome2MousePressed
        this.dispose();
    }//GEN-LAST:event_btnHome2MousePressed

    // Métodos jPanel2MouseDragged e jPanel2MousePressed são para mover a tela
    private void jPanel2MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel2MouseDragged
        // src to drag
        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();
        this.setLocation(x - xx, y - xy);
    }//GEN-LAST:event_jPanel2MouseDragged

    int xx, xy;
    private void jPanel2MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel2MousePressed
        // drag this pane
        xx = evt.getX();
        xy = evt.getY();
    }//GEN-LAST:event_jPanel2MousePressed

    private void btnPesquisa2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPesquisa2ActionPerformed
        PagamentoDAO pagamentoDAO = new PagamentoDAO();
        //UsuarioDAO usuarioDAO = new UsuarioDAO();

        if (!txtNomeCliente2.equals("")) {
            try {
                ArrayList<Pagamento> pagamentos = PagamentoDAO.listarPorNome(txtNomeCliente2.getText().trim());
                pagamentoTableModel = new PagamentoTableModel(pagamentos);
                tableListaPagamentos.setModel(pagamentoTableModel);
                UsuarioDAO usuarioDAO = new UsuarioDAO();
                ArrayList<Usuario> usuarios = UsuarioDAO.listarPorNome(txtNomeCliente2.getText().trim());
                this.pagamentoTableModel.addListaNova(usuarios);
            } catch (Exception ex) {
                Logger.getLogger(FormPagamentos.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_btnPesquisa2ActionPerformed

    private void btnPesquisarValorTotalMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnPesquisarValorTotalMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_btnPesquisarValorTotalMouseClicked

    private void btnPesquisarNomeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnPesquisarNomeMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_btnPesquisarNomeMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormPagamentos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormPagamentos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormPagamentos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormPagamentos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormPagamentos().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup bgOpcao1;
    private javax.swing.JLabel btnHome2;
    private java.awt.Button btnImprimir1;
    private java.awt.Button btnPesquisa2;
    private javax.swing.JLabel btnPesquisarNome;
    private javax.swing.JLabel btnPesquisarValorTotal;
    private java.awt.Choice choiceAno1;
    private java.awt.Choice choiceDia1;
    private java.awt.Choice choiceMes1;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField jTFTotal1;
    private javax.swing.JRadioButton jrbAno1;
    private javax.swing.JRadioButton jrbDia1;
    private javax.swing.JRadioButton jrbMes1;
    private javax.swing.JTable tableFormaPagamento1;
    private javax.swing.JTable tableListaPagamentos;
    private javax.swing.JTextField txtNomeCliente2;
    // End of variables declaration//GEN-END:variables
}
