/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.legourmet.view;

import br.com.legourmet.dao.UsuarioDAO;
import br.com.legourmet.model.Usuario;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import org.apache.commons.codec.digest.DigestUtils;

/**
 *
 * @author gouri
 */
public class FormEditarUsuario extends javax.swing.JFrame {

    /**
     * Creates new form FormNovoItem
     */
    public FormEditarUsuario() {
        initComponents();
        this.setResizable(false);
        this.setLocationRelativeTo(null);//Tela centralizada
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bgSituacao5 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        btnFechar5 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        choicePerfil5 = new java.awt.Choice();
        jLabel20 = new javax.swing.JLabel();
        txtNome5 = new javax.swing.JTextField();
        jLabel22 = new javax.swing.JLabel();
        jrbAtivo5 = new javax.swing.JRadioButton();
        jrbBloqueado5 = new javax.swing.JRadioButton();
        btnSalvar5 = new java.awt.Button();
        btnCancelar5 = new java.awt.Button();
        btnLimpar5 = new java.awt.Button();
        jLabel2 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        txtLogin5 = new javax.swing.JTextField();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        txtSenha5 = new javax.swing.JPasswordField();
        txtConfirmarSenha5 = new javax.swing.JPasswordField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(24, 34, 56));

        jPanel2.setBackground(new java.awt.Color(239, 152, 43));
        jPanel2.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                jPanel2MouseDragged(evt);
            }
        });
        jPanel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jPanel2MousePressed(evt);
            }
        });

        btnFechar5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/legourmet/imgs/icons8_Close_Window_25px_2.png"))); // NOI18N
        btnFechar5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnFechar5MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnFechar5)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnFechar5, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
        );

        jLabel3.setForeground(new java.awt.Color(102, 102, 102));
        jLabel3.setText("Perfil");

        choicePerfil5.setBackground(new java.awt.Color(239, 152, 43));

        jLabel20.setForeground(new java.awt.Color(102, 102, 102));
        jLabel20.setText("Nome");

        txtNome5.setBackground(new java.awt.Color(239, 152, 43));
        txtNome5.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        txtNome5.setForeground(new java.awt.Color(255, 255, 255));
        txtNome5.setBorder(null);
        txtNome5.setCaretColor(new java.awt.Color(255, 255, 255));
        txtNome5.setPreferredSize(new java.awt.Dimension(2, 20));

        jLabel22.setForeground(new java.awt.Color(102, 102, 102));
        jLabel22.setText("Situação");

        jrbAtivo5.setBackground(new java.awt.Color(24, 34, 56));
        bgSituacao5.add(jrbAtivo5);
        jrbAtivo5.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        jrbAtivo5.setForeground(new java.awt.Color(255, 255, 255));
        jrbAtivo5.setSelected(true);
        jrbAtivo5.setText("Ativo");

        jrbBloqueado5.setBackground(new java.awt.Color(24, 34, 56));
        bgSituacao5.add(jrbBloqueado5);
        jrbBloqueado5.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        jrbBloqueado5.setForeground(new java.awt.Color(255, 255, 255));
        jrbBloqueado5.setText("Bloqueado");

        btnSalvar5.setBackground(new java.awt.Color(249, 189, 0));
        btnSalvar5.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        btnSalvar5.setForeground(new java.awt.Color(24, 34, 56));
        btnSalvar5.setLabel("SALVAR ALTERAÇÕES");
        btnSalvar5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalvar5ActionPerformed(evt);
            }
        });

        btnCancelar5.setBackground(new java.awt.Color(249, 189, 0));
        btnCancelar5.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        btnCancelar5.setForeground(new java.awt.Color(24, 34, 56));
        btnCancelar5.setLabel("CANCELAR");
        btnCancelar5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnCancelar5MouseClicked(evt);
            }
        });

        btnLimpar5.setBackground(new java.awt.Color(249, 189, 0));
        btnLimpar5.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        btnLimpar5.setForeground(new java.awt.Color(24, 34, 56));
        btnLimpar5.setLabel("LIMPAR");
        btnLimpar5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnLimpar5MouseClicked(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(102, 102, 102));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Editar Usuário");

        jLabel23.setForeground(new java.awt.Color(102, 102, 102));
        jLabel23.setText("Login");

        txtLogin5.setBackground(new java.awt.Color(239, 152, 43));
        txtLogin5.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        txtLogin5.setForeground(new java.awt.Color(255, 255, 255));
        txtLogin5.setBorder(null);
        txtLogin5.setCaretColor(new java.awt.Color(255, 255, 255));
        txtLogin5.setPreferredSize(new java.awt.Dimension(2, 20));

        jLabel24.setForeground(new java.awt.Color(102, 102, 102));
        jLabel24.setText("Senha");

        jLabel25.setForeground(new java.awt.Color(102, 102, 102));
        jLabel25.setText("Digite a senha novamente");

        txtSenha5.setBackground(new java.awt.Color(239, 152, 43));
        txtSenha5.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        txtSenha5.setForeground(new java.awt.Color(255, 255, 255));
        txtSenha5.setBorder(null);

        txtConfirmarSenha5.setBackground(new java.awt.Color(239, 152, 43));
        txtConfirmarSenha5.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        txtConfirmarSenha5.setForeground(new java.awt.Color(255, 255, 255));
        txtConfirmarSenha5.setBorder(null);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 555, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel25)
                            .addComponent(jLabel24)
                            .addComponent(jLabel23)
                            .addComponent(jLabel3)
                            .addComponent(jLabel20)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jrbAtivo5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jrbBloqueado5))
                            .addComponent(jLabel22)
                            .addComponent(txtNome5, javax.swing.GroupLayout.PREFERRED_SIZE, 227, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(choicePerfil5, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(txtConfirmarSenha5, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(txtSenha5, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(txtLogin5, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(161, 161, 161))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(btnSalvar5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnLimpar5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(57, 57, 57)
                        .addComponent(btnCancelar5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(27, 27, 27))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addGap(35, 35, 35)
                .addComponent(jLabel3)
                .addGap(1, 1, 1)
                .addComponent(choicePerfil5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel20)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtNome5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel23)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtLogin5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(13, 13, 13)
                .addComponent(jLabel24)
                .addGap(5, 5, 5)
                .addComponent(txtSenha5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel25)
                .addGap(5, 5, 5)
                .addComponent(txtConfirmarSenha5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel22)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jrbAtivo5)
                    .addComponent(jrbBloqueado5))
                .addGap(26, 26, 26)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnCancelar5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnLimpar5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSalvar5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(40, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 500));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSalvar5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalvar5ActionPerformed
        Usuario usuario = null;

        if (txtNome5.equals("")) {
            JOptionPane.showMessageDialog(this,
                    "Nome Obrigatório");
            txtNome5.requestFocus();
            return;
        } else if (txtLogin5.equals("")) {
            JOptionPane.showMessageDialog(this,
                    "Login Obrigatório");
            txtLogin5.requestFocus();
            return;
        } else if (txtSenha5.equals("")) {
            JOptionPane.showMessageDialog(this,
                    "Senha Obrigatória");
            txtSenha5.requestFocus();
            return;
        } else if (txtSenha5.equals(txtConfirmarSenha5)) {
            JOptionPane.showMessageDialog(this,
                    "As senhas precisam ser iguais");
            txtSenha5.setText("");
            txtConfirmarSenha5.setText("");
            txtSenha5.requestFocus();
            return;
        }else{
            usuario = new Usuario();
        }
        usuario.setNome(txtNome5.getText());
        usuario.setPerfil(choicePerfil5.getSelectedItem());
        usuario.setLogin(txtLogin5.getText());
        String senhaCriptografada = DigestUtils.sha512Hex(txtSenha5.toString());
        usuario.setSenha(senhaCriptografada);
        if(jrbAtivo5.isSelected()){
            usuario.setPerfil(jrbAtivo5.getText());
        }else{
            usuario.setPerfil(jrbBloqueado5.getText());
        }
        
        try {
            UsuarioDAO.alterar(usuario);
            JOptionPane.showMessageDialog(this,
                "Dados salvos com sucesso!");
            dispose();
        } catch (Exception ex) {
            Logger.getLogger(FormNovoUsuario.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(this, ex.getMessage(), "Erro", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnSalvar5ActionPerformed

    private void btnFechar5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnFechar5MouseClicked
        int resposta = JOptionPane.showConfirmDialog(null, "Alterações não serão salvas.\nDeseja Realmente sair?", "Sair", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);
        if (resposta == JOptionPane.YES_OPTION) {
            this.dispose();
        }
    }//GEN-LAST:event_btnFechar5MouseClicked

    private void btnCancelar5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCancelar5MouseClicked
        int resposta = JOptionPane.showConfirmDialog(null, "Alterações não serão salvas.\nDeseja Realmente sair?", "Sair", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);
        if (resposta == JOptionPane.YES_OPTION) {
            this.dispose();
        }
    }//GEN-LAST:event_btnCancelar5MouseClicked

    // Métodos jPanel2MouseDragged e jPanel2MousePressed são para mover a tela
    private void jPanel2MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel2MouseDragged
        // src to drag
        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();
        this.setLocation(x-xx, y-xy);
    }//GEN-LAST:event_jPanel2MouseDragged

    int xx, xy;
    private void jPanel2MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel2MousePressed
        // drag this pane
        xx = evt.getX();
        xy = evt.getY();
    }//GEN-LAST:event_jPanel2MousePressed

    private void btnLimpar5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnLimpar5MouseClicked
        
    }//GEN-LAST:event_btnLimpar5MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Windows look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormEditarUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormEditarUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormEditarUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormEditarUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormEditarUsuario().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup bgSituacao5;
    private java.awt.Button btnCancelar5;
    private javax.swing.JLabel btnFechar5;
    private java.awt.Button btnLimpar5;
    private java.awt.Button btnSalvar5;
    private java.awt.Choice choicePerfil5;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JRadioButton jrbAtivo5;
    private javax.swing.JRadioButton jrbBloqueado5;
    private javax.swing.JPasswordField txtConfirmarSenha5;
    private javax.swing.JTextField txtLogin5;
    private javax.swing.JTextField txtNome5;
    private javax.swing.JPasswordField txtSenha5;
    // End of variables declaration//GEN-END:variables
}
