/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.legourmet.view;

import br.com.legourmet.dao.UsuarioDAO;
import br.com.legourmet.model.Usuario;
import br.com.legourmet.model.UsuarioTableModel;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author gouri
 */
public class FormUsuarios extends javax.swing.JFrame {

    private UsuarioTableModel usuarioTableModel;

    private void prepararTable() {
        UsuarioDAO usuarioDAO = new UsuarioDAO();
        ArrayList<Usuario> usuarios = new ArrayList<>();
        try {
            usuarios = usuarioDAO.listar();
        } catch (Exception ex) {
            Logger.getLogger(FormCardapio.class.getName()).log(Level.SEVERE, null, ex);
        }
        //pesquisar clientes cadastrados no banco de dados
        usuarioTableModel = new UsuarioTableModel(usuarios);
        jTable2.setModel(usuarioTableModel);
    }
    
    /**
     * Creates new form FormPrincipalAdmin
     */
    public FormUsuarios() {
        initComponents();
        this.setResizable(false);
        this.setLocationRelativeTo(null);//Tela centralizada
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bgSituacao2 = new javax.swing.ButtonGroup();
        jPanel2 = new javax.swing.JPanel();
        btnHome4 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jLabel9 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        btnAddUsuario1 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        btnBloqueioUser1 = new javax.swing.JLabel();
        btnEditUsuario1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        btnPesquisarPerfil = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        txtNome2 = new javax.swing.JTextField();
        btnPesquisarNome = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        btnPesquisa4 = new java.awt.Button();
        choicePerfil4 = new java.awt.Choice();
        jLabel24 = new javax.swing.JLabel();
        jrbAtivo = new javax.swing.JRadioButton();
        jrbBloqueado = new javax.swing.JRadioButton();
        jrbTodos1 = new javax.swing.JRadioButton();
        btnPesquisarSituacao = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(239, 152, 43));
        jPanel2.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                jPanel2MouseDragged(evt);
            }
        });
        jPanel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jPanel2MousePressed(evt);
            }
        });

        btnHome4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/legourmet/imgs/icons8_Home_25px.png"))); // NOI18N
        btnHome4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnHome4MousePressed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(1175, Short.MAX_VALUE)
                .addComponent(btnHome4)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnHome4, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1210, 40));

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jScrollPane2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));

        jTable2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));
        jTable2.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"Caixa",  new Integer(1), "Luiza da Silva", "luiza.silva", "12/11/18", "Ativo"},
                {"Administrador",  new Integer(2), "Marcos Rocha", "marcos.rocha", "10/11/18", "Ativo"},
                {"Cozinha",  new Integer(5), "Gabriela Ferreira", "gabriela.ferreira", "18/12/18", "Bloqueado"},
                {"Administrador",  new Integer(10), "Thiago Alves", "thiago.alves", "10/12/18", "Ativo"}
            },
            new String [] {
                "Perfil", "Identificador", "Nome", "Login", "Último Acesso", "Situação"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable2.setGridColor(new java.awt.Color(255, 255, 255));
        jTable2.setRowHeight(22);
        jTable2.setSelectionBackground(new java.awt.Color(255, 96, 2));
        jScrollPane2.setViewportView(jTable2);

        jPanel3.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 70, 895, 610));

        jLabel9.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(102, 102, 102));
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setText("Lista de Usuários");
        jPanel3.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(43, 20, 890, -1));

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 40, 970, 720));

        jPanel4.setBackground(new java.awt.Color(249, 189, 0));

        btnAddUsuario1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/legourmet/imgs/icons8_Add_User_Male_25px.png"))); // NOI18N
        btnAddUsuario1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnAddUsuario1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnAddUsuario1MouseClicked(evt);
            }
        });

        btnBloqueioUser1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/legourmet/imgs/icons8_Lock_25px_2.png"))); // NOI18N
        btnBloqueioUser1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnBloqueioUser1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnBloqueioUser1MouseClicked(evt);
            }
        });

        btnEditUsuario1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/legourmet/imgs/icons8_Registration_25px.png"))); // NOI18N
        btnEditUsuario1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnEditUsuario1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnEditUsuario1MouseClicked(evt);
            }
        });

        jLabel3.setForeground(new java.awt.Color(102, 102, 102));
        jLabel3.setText("Perfil");

        btnPesquisarPerfil.setForeground(new java.awt.Color(102, 102, 102));
        btnPesquisarPerfil.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/legourmet/imgs/icons8_Search_18px.png"))); // NOI18N
        btnPesquisarPerfil.setText("Pesquisar");
        btnPesquisarPerfil.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnPesquisarPerfil.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnPesquisarPerfilMouseClicked(evt);
            }
        });

        jLabel20.setForeground(new java.awt.Color(102, 102, 102));
        jLabel20.setText("Nome");

        txtNome2.setBackground(new java.awt.Color(239, 152, 43));
        txtNome2.setForeground(new java.awt.Color(255, 255, 255));
        txtNome2.setBorder(null);
        txtNome2.setCaretColor(new java.awt.Color(255, 255, 255));
        txtNome2.setPreferredSize(new java.awt.Dimension(2, 20));
        txtNome2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNome2ActionPerformed(evt);
            }
        });

        btnPesquisarNome.setForeground(new java.awt.Color(102, 102, 102));
        btnPesquisarNome.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/legourmet/imgs/icons8_Search_18px.png"))); // NOI18N
        btnPesquisarNome.setText("Pesquisar");
        btnPesquisarNome.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnPesquisarNome.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnPesquisarNomeMouseClicked(evt);
            }
        });

        jLabel14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/legourmet/imgs/icons8_Find_User_Male_35px.png"))); // NOI18N

        btnPesquisa4.setBackground(new java.awt.Color(249, 189, 0));
        btnPesquisa4.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        btnPesquisa4.setForeground(new java.awt.Color(102, 102, 102));
        btnPesquisa4.setLabel("PESQUISAR");
        btnPesquisa4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPesquisa4ActionPerformed(evt);
            }
        });

        choicePerfil4.setBackground(new java.awt.Color(239, 152, 43));

        jLabel24.setForeground(new java.awt.Color(102, 102, 102));
        jLabel24.setText("Situação");

        jrbAtivo.setBackground(new java.awt.Color(249, 189, 0));
        bgSituacao2.add(jrbAtivo);
        jrbAtivo.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        jrbAtivo.setForeground(new java.awt.Color(102, 102, 102));
        jrbAtivo.setText("Ativo");

        jrbBloqueado.setBackground(new java.awt.Color(249, 189, 0));
        bgSituacao2.add(jrbBloqueado);
        jrbBloqueado.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        jrbBloqueado.setForeground(new java.awt.Color(102, 102, 102));
        jrbBloqueado.setText("Bloqueado");

        jrbTodos1.setBackground(new java.awt.Color(249, 189, 0));
        bgSituacao2.add(jrbTodos1);
        jrbTodos1.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        jrbTodos1.setForeground(new java.awt.Color(102, 102, 102));
        jrbTodos1.setSelected(true);
        jrbTodos1.setText("Todos");

        btnPesquisarSituacao.setForeground(new java.awt.Color(102, 102, 102));
        btnPesquisarSituacao.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/legourmet/imgs/icons8_Search_18px.png"))); // NOI18N
        btnPesquisarSituacao.setText("Pesquisar");
        btnPesquisarSituacao.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnPesquisarSituacao.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnPesquisarSituacaoMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 218, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(108, 108, 108)
                        .addComponent(jLabel14))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(100, 100, 100)
                        .addComponent(jLabel24))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(43, 43, 43)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel3)
                            .addComponent(choicePerfil4, javax.swing.GroupLayout.DEFAULT_SIZE, 160, Short.MAX_VALUE)
                            .addComponent(jLabel20)
                            .addComponent(txtNome2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap(12, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                        .addComponent(btnAddUsuario1)
                        .addGap(18, 18, 18)
                        .addComponent(btnEditUsuario1)
                        .addGap(18, 18, 18)
                        .addComponent(btnBloqueioUser1)
                        .addGap(61, 61, 61))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                        .addComponent(btnPesquisa4, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(56, 56, 56))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btnPesquisarSituacao)
                            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel4Layout.createSequentialGroup()
                                    .addGap(56, 56, 56)
                                    .addComponent(btnPesquisarPerfil))
                                .addGroup(jPanel4Layout.createSequentialGroup()
                                    .addComponent(jrbAtivo)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jrbBloqueado))
                                .addComponent(btnPesquisarNome, javax.swing.GroupLayout.Alignment.TRAILING)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jrbTodos1)
                        .addGap(22, 22, 22))))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnAddUsuario1)
                    .addComponent(btnBloqueioUser1)
                    .addComponent(btnEditUsuario1))
                .addGap(18, 18, 18)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(jLabel14)
                .addGap(18, 18, 18)
                .addComponent(jLabel3)
                .addGap(2, 2, 2)
                .addComponent(choicePerfil4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnPesquisarPerfil)
                .addGap(33, 33, 33)
                .addComponent(jLabel20)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtNome2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnPesquisarNome)
                .addGap(51, 51, 51)
                .addComponent(jLabel24)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jrbAtivo)
                    .addComponent(jrbBloqueado)
                    .addComponent(jrbTodos1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnPesquisarSituacao)
                .addGap(48, 48, 48)
                .addComponent(btnPesquisa4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(190, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 40, 240, 720));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    // Volta para FormPrincipal
    private void btnHome4MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnHome4MousePressed
        this.dispose();
    }//GEN-LAST:event_btnHome4MousePressed

    // Abre FormNovoUsuario
    private void btnAddUsuario1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAddUsuario1MouseClicked
        FormNovoUsuario janela = new FormNovoUsuario();
        //this.setEnabled(false);
        janela.setVisible(true);
    }//GEN-LAST:event_btnAddUsuario1MouseClicked

    //Abre FormEditarUsuario
    private void btnEditUsuario1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEditUsuario1MouseClicked
        FormEditarUsuario janela = new FormEditarUsuario();
       // this.setEnabled(false);
        janela.setVisible(true);
    }//GEN-LAST:event_btnEditUsuario1MouseClicked

    // Bloqueia/Desbloqueia Usuário
    private void btnBloqueioUser1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnBloqueioUser1MouseClicked
        //Bloquear/Desbloquear Usuário
        
        //Mostrar Mensagem de que usuário foi bloqueado/desbloqueado
    }//GEN-LAST:event_btnBloqueioUser1MouseClicked

    // Métodos jPanel2MouseDragged e jPanel2MousePressed são para mover a tela
    private void jPanel2MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel2MouseDragged
        // src to drag
        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();
        this.setLocation(x-xx, y-xy);
    }//GEN-LAST:event_jPanel2MouseDragged

    int xx, xy;
    private void jPanel2MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel2MousePressed
        // drag this pane
        xx = evt.getX();
        xy = evt.getY();
    }//GEN-LAST:event_jPanel2MousePressed

    private void btnPesquisa4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPesquisa4ActionPerformed
        UsuarioDAO usuarioDAO = new UsuarioDAO();

        if (!txtNome2.equals("")) {
            try {
                ArrayList<Usuario> usuarios = usuarioDAO.listarPorNome(txtNome2.getText().trim());
                usuarioTableModel = new UsuarioTableModel(usuarios);
                jTable2.setModel(usuarioTableModel);
            } catch (Exception ex) {
                Logger.getLogger(FormUsuarios.class.getName()).log(Level.SEVERE, null, ex);
            }

        } else if (!choicePerfil4.equals("")) {
            try {
                ArrayList<Usuario> usuarios = usuarioDAO.listarPorPerfil(choicePerfil4.getSelectedItem());
                usuarioTableModel = new UsuarioTableModel(usuarios);
                jTable2.setModel(usuarioTableModel);
            } catch (Exception ex) {
                Logger.getLogger(FormUsuarios.class.getName()).log(Level.SEVERE, null, ex);
            }
        } else if (jrbAtivo.isSelected()) {
            try {
                ArrayList<Usuario> usuarios = usuarioDAO.listarPorSituacao("1");
                usuarioTableModel = new UsuarioTableModel(usuarios);
                jTable2.setModel(usuarioTableModel);
            } catch (Exception ex) {
                Logger.getLogger(FormCardapio.class.getName()).log(Level.SEVERE, null, ex);
            }
        } else if (jrbBloqueado.isSelected()) {
            try {
                ArrayList<Usuario> usuarios = usuarioDAO.listarPorSituacao("0");
                usuarioTableModel = new UsuarioTableModel(usuarios);
                jTable2.setModel(usuarioTableModel);
            } catch (Exception ex) {
                Logger.getLogger(FormCardapio.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_btnPesquisa4ActionPerformed

    private void txtNome2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNome2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNome2ActionPerformed

    private void btnPesquisarPerfilMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnPesquisarPerfilMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_btnPesquisarPerfilMouseClicked

    private void btnPesquisarNomeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnPesquisarNomeMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_btnPesquisarNomeMouseClicked

    private void btnPesquisarSituacaoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnPesquisarSituacaoMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_btnPesquisarSituacaoMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Windows look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormUsuarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormUsuarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormUsuarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormUsuarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormUsuarios().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup bgSituacao2;
    private javax.swing.JLabel btnAddUsuario1;
    private javax.swing.JLabel btnBloqueioUser1;
    private javax.swing.JLabel btnEditUsuario1;
    private javax.swing.JLabel btnHome4;
    private java.awt.Button btnPesquisa4;
    private javax.swing.JLabel btnPesquisarNome;
    private javax.swing.JLabel btnPesquisarPerfil;
    private javax.swing.JLabel btnPesquisarSituacao;
    private java.awt.Choice choicePerfil4;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTable jTable2;
    private javax.swing.JRadioButton jrbAtivo;
    private javax.swing.JRadioButton jrbBloqueado;
    private javax.swing.JRadioButton jrbTodos1;
    private javax.swing.JTextField txtNome2;
    // End of variables declaration//GEN-END:variables
}
