/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.legourmet.view;

import br.com.legourmet.dao.ItemDAO;
import br.com.legourmet.model.Item;
import java.io.File;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileNameExtensionFilter;

/**
 *
 * @author gouri
 */
public class FormEditarItem extends javax.swing.JFrame {

    /**
     * Creates new form FormNovoItem
     */
    public FormEditarItem() {
        initComponents();
        this.setResizable(false);
        this.setLocationRelativeTo(null);//Tela centralizada
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bgDisponivel6 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        btnFechar6 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        choiceCategoria6 = new java.awt.Choice();
        jLabel20 = new javax.swing.JLabel();
        txtItem6 = new javax.swing.JTextField();
        jLabel21 = new javax.swing.JLabel();
        txtIngredientes6 = new javax.swing.JTextField();
        jLabel22 = new javax.swing.JLabel();
        jrbDisponivel6 = new javax.swing.JRadioButton();
        jrbIndisponivel6 = new javax.swing.JRadioButton();
        btnSalvarAlteracoes = new java.awt.Button();
        btnCancelar6 = new java.awt.Button();
        btnLimpar = new java.awt.Button();
        jLabel2 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        txtTempoPreparo6 = new javax.swing.JTextField();
        btnAlterarImg = new java.awt.Button();
        jLabel24 = new javax.swing.JLabel();
        txtValor5 = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(24, 34, 56));

        jPanel2.setBackground(new java.awt.Color(239, 152, 43));
        jPanel2.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                jPanel2MouseDragged(evt);
            }
        });
        jPanel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jPanel2MousePressed(evt);
            }
        });

        btnFechar6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/legourmet/imgs/icons8_Close_Window_25px_2.png"))); // NOI18N
        btnFechar6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnFechar6MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnFechar6)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnFechar6, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
        );

        jLabel3.setForeground(new java.awt.Color(102, 102, 102));
        jLabel3.setText("Categoria");

        choiceCategoria6.setBackground(new java.awt.Color(239, 152, 43));
        choiceCategoria6.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N

        jLabel20.setForeground(new java.awt.Color(102, 102, 102));
        jLabel20.setText("Item");

        txtItem6.setBackground(new java.awt.Color(239, 152, 43));
        txtItem6.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        txtItem6.setForeground(new java.awt.Color(255, 255, 255));
        txtItem6.setBorder(null);
        txtItem6.setCaretColor(new java.awt.Color(255, 255, 255));
        txtItem6.setPreferredSize(new java.awt.Dimension(2, 20));

        jLabel21.setForeground(new java.awt.Color(102, 102, 102));
        jLabel21.setText("Ingredientes:");

        txtIngredientes6.setBackground(new java.awt.Color(239, 152, 43));
        txtIngredientes6.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        txtIngredientes6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtIngredientes6ActionPerformed(evt);
            }
        });

        jLabel22.setForeground(new java.awt.Color(102, 102, 102));
        jLabel22.setText("Disponível:");

        jrbDisponivel6.setBackground(new java.awt.Color(24, 34, 56));
        bgDisponivel6.add(jrbDisponivel6);
        jrbDisponivel6.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        jrbDisponivel6.setForeground(new java.awt.Color(255, 255, 255));
        jrbDisponivel6.setSelected(true);
        jrbDisponivel6.setText("Disponível");

        jrbIndisponivel6.setBackground(new java.awt.Color(24, 34, 56));
        bgDisponivel6.add(jrbIndisponivel6);
        jrbIndisponivel6.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        jrbIndisponivel6.setForeground(new java.awt.Color(255, 255, 255));
        jrbIndisponivel6.setText("Indisponível");

        btnSalvarAlteracoes.setBackground(new java.awt.Color(249, 189, 0));
        btnSalvarAlteracoes.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        btnSalvarAlteracoes.setForeground(new java.awt.Color(24, 34, 56));
        btnSalvarAlteracoes.setLabel("SALVAR ALTERAÇÕES");
        btnSalvarAlteracoes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalvarAlteracoesActionPerformed(evt);
            }
        });

        btnCancelar6.setBackground(new java.awt.Color(249, 189, 0));
        btnCancelar6.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        btnCancelar6.setForeground(new java.awt.Color(24, 34, 56));
        btnCancelar6.setLabel("CANCELAR");
        btnCancelar6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnCancelar6MouseClicked(evt);
            }
        });

        btnLimpar.setBackground(new java.awt.Color(249, 189, 0));
        btnLimpar.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        btnLimpar.setForeground(new java.awt.Color(24, 34, 56));
        btnLimpar.setLabel("LIMPAR");
        btnLimpar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnLimparMouseClicked(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(102, 102, 102));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Editar Item");

        jLabel23.setForeground(new java.awt.Color(102, 102, 102));
        jLabel23.setText("Tempo de Preparo (Estimativa)");

        txtTempoPreparo6.setBackground(new java.awt.Color(239, 152, 43));
        txtTempoPreparo6.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        txtTempoPreparo6.setForeground(new java.awt.Color(255, 255, 255));
        txtTempoPreparo6.setBorder(null);
        txtTempoPreparo6.setCaretColor(new java.awt.Color(255, 255, 255));
        txtTempoPreparo6.setPreferredSize(new java.awt.Dimension(2, 20));

        btnAlterarImg.setBackground(new java.awt.Color(249, 189, 0));
        btnAlterarImg.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        btnAlterarImg.setForeground(new java.awt.Color(24, 34, 56));
        btnAlterarImg.setLabel("ALTERAR IMAGEM");
        btnAlterarImg.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnAlterarImgMouseClicked(evt);
            }
        });

        jLabel24.setForeground(new java.awt.Color(102, 102, 102));
        jLabel24.setText("Valor:");

        txtValor5.setBackground(new java.awt.Color(239, 152, 43));
        txtValor5.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        txtValor5.setForeground(new java.awt.Color(255, 255, 255));
        txtValor5.setBorder(null);
        txtValor5.setCaretColor(new java.awt.Color(255, 255, 255));
        txtValor5.setPreferredSize(new java.awt.Dimension(2, 20));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 555, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(btnSalvarAlteracoes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnLimpar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(32, 32, 32)
                        .addComponent(btnCancelar6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(36, 36, 36))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel23)
                                    .addComponent(txtTempoPreparo6, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jrbDisponivel6)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jrbIndisponivel6))
                                    .addComponent(jLabel22)
                                    .addComponent(jLabel24)
                                    .addComponent(txtValor5, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addComponent(btnAlterarImg, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jLabel3)
                                .addComponent(jLabel20)
                                .addComponent(txtIngredientes6)
                                .addComponent(jLabel21)
                                .addComponent(txtItem6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(choiceCategoria6, javax.swing.GroupLayout.PREFERRED_SIZE, 227, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(163, 163, 163))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addGap(31, 31, 31)
                .addComponent(jLabel3)
                .addGap(1, 1, 1)
                .addComponent(choiceCategoria6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel20)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtItem6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel21)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtIngredientes6, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel24)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtValor5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 24, Short.MAX_VALUE)
                .addComponent(jLabel23)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtTempoPreparo6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel22)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jrbDisponivel6)
                    .addComponent(jrbIndisponivel6))
                .addGap(43, 43, 43)
                .addComponent(btnAlterarImg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(52, 52, 52)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnCancelar6, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnLimpar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSalvarAlteracoes, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(48, 48, 48))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 650));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtIngredientes6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtIngredientes6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtIngredientes6ActionPerformed

    private void btnFechar6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnFechar6MouseClicked
        int resposta = JOptionPane.showConfirmDialog(null, "Alterações não serão salvas.\nDeseja Realmente sair?", "Sair", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);
        if (resposta == JOptionPane.YES_OPTION) {
            this.dispose();
        }
    }//GEN-LAST:event_btnFechar6MouseClicked

    private void btnCancelar6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCancelar6MouseClicked
        int resposta = JOptionPane.showConfirmDialog(null, "Alterações não serão salvas.\nDeseja Realmente sair?", "Sair", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);
        if (resposta == JOptionPane.YES_OPTION) {
            this.dispose();
        }
    }//GEN-LAST:event_btnCancelar6MouseClicked

    // Métodos jPanel2MouseDragged e jPanel2MousePressed são para mover a tela
    private void jPanel2MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel2MouseDragged
        // src to drag
        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();
        this.setLocation(x-xx, y-xy);
    }//GEN-LAST:event_jPanel2MouseDragged

     int xx, xy;
    private void jPanel2MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel2MousePressed
        // drag this pane
        xx = evt.getX();
        xy = evt.getY();
    }//GEN-LAST:event_jPanel2MousePressed

    //Alterar imagem do Item
    private void btnAlterarImgMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAlterarImgMouseClicked
       JFileChooser fileChooser = new JFileChooser();
        fileChooser.setCurrentDirectory(new File(System.getProperty("user.home")));
        FileNameExtensionFilter filter = new FileNameExtensionFilter("*.IMAGE", "jpg", "gif", "png");
        fileChooser.addChoosableFileFilter(filter);
        int result = fileChooser.showSaveDialog(null);
        if(result == JFileChooser.APPROVE_OPTION){
            File selectedFile = fileChooser.getSelectedFile();
            String path = selectedFile.getAbsolutePath();
//            label.setIcon(ResizeImage(path));
        } else if(result == JFileChooser.CANCEL_OPTION){
            System.out.println("Nenhum arquivo foi escolhido");
        }
    }//GEN-LAST:event_btnAlterarImgMouseClicked

    private void btnSalvarAlteracoesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalvarAlteracoesActionPerformed
        Item item = null;

        if (txtItem6.equals("")) {
            JOptionPane.showMessageDialog(this, "Item Obrigatório!");
            txtItem6.requestFocus();
            return;
        } else if (txtIngredientes6.equals("")) {
            JOptionPane.showMessageDialog(this, "Ingrediente Obrigatório!");
            txtIngredientes6.requestFocus();
            return;
        } else if (txtTempoPreparo6.equals("")) {
            JOptionPane.showMessageDialog(this, "Tempo estimado de preparo é Obrigatório!");
            txtTempoPreparo6.requestFocus();
            return;
        } else{
            item = new Item();
        }
        item.setNome_Item(txtItem6.getText());
        item.setIngredientes(txtIngredientes6.getText());
        item.setTempo_Preparo_Item(txtTempoPreparo6.getText());
        item.setCategoria(choiceCategoria6.getSelectedItem());
        
        try {
            ItemDAO.alterar(item);
            JOptionPane.showMessageDialog(this,
                "Dados alterados com sucesso!");
            dispose();
        } catch (Exception ex) {
            Logger.getLogger(FormNovoItem.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(this, ex.getMessage(), "erro", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnSalvarAlteracoesActionPerformed

    private void btnLimparMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnLimparMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_btnLimparMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Windows look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormEditarItem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormEditarItem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormEditarItem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormEditarItem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormEditarItem().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup bgDisponivel6;
    private java.awt.Button btnAlterarImg;
    private java.awt.Button btnCancelar6;
    private javax.swing.JLabel btnFechar6;
    private java.awt.Button btnLimpar;
    private java.awt.Button btnSalvarAlteracoes;
    private java.awt.Choice choiceCategoria6;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JRadioButton jrbDisponivel6;
    private javax.swing.JRadioButton jrbIndisponivel6;
    private javax.swing.JTextField txtIngredientes6;
    private javax.swing.JTextField txtItem6;
    private javax.swing.JTextField txtTempoPreparo6;
    private javax.swing.JTextField txtValor5;
    // End of variables declaration//GEN-END:variables
}
