/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.legourmet.view;

import javax.swing.JOptionPane;

/**
 *
 * @author gouri
 */
public class FormPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form FormPrincipalAdmin
     */
    public FormPrincipal() {
        initComponents();
        //this.setEnabled(true);
        this.setResizable(false);
        //setExtendedState(MAXIMIZED_BOTH); // Tela cheia
        this.setLocationRelativeTo(null); // Tela centralizada
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLNomeUsuario1 = new javax.swing.JLabel();
        jTFPerfil1 = new javax.swing.JTextField();
        btnPanelPedidos1 = new javax.swing.JPanel();
        ind_7 = new javax.swing.JPanel();
        jLPedidos1 = new javax.swing.JLabel();
        btnPanelPagamentos1 = new javax.swing.JPanel();
        ind_8 = new javax.swing.JPanel();
        jLPagamentos1 = new javax.swing.JLabel();
        btnPanelCardapio1 = new javax.swing.JPanel();
        ind_9 = new javax.swing.JPanel();
        jLCardapio1 = new javax.swing.JLabel();
        btnPanelUsuarios1 = new javax.swing.JPanel();
        ind_10 = new javax.swing.JPanel();
        jLUsuarios1 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        btnDeslogar1 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(24, 34, 56));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/legourmet/imgs/icons8_Customer_50px.png"))); // NOI18N

        jLNomeUsuario1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLNomeUsuario1.setForeground(new java.awt.Color(255, 255, 255));
        jLNomeUsuario1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLNomeUsuario1.setText("Paula Souza");

        jTFPerfil1.setEditable(false);
        jTFPerfil1.setBackground(new java.awt.Color(239, 190, 79));
        jTFPerfil1.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        jTFPerfil1.setForeground(new java.awt.Color(255, 255, 255));
        jTFPerfil1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTFPerfil1.setText("Administrador");
        jTFPerfil1.setBorder(null);
        jTFPerfil1.setCaretColor(new java.awt.Color(255, 255, 255));
        jTFPerfil1.setPreferredSize(new java.awt.Dimension(2, 20));

        btnPanelPedidos1.setBackground(new java.awt.Color(24, 38, 69));
        btnPanelPedidos1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnPanelPedidos1.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                btnPanelPedidos1MouseMoved(evt);
            }
        });
        btnPanelPedidos1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnPanelPedidos1MousePressed(evt);
            }
        });

        ind_7.setPreferredSize(new java.awt.Dimension(3, 42));

        javax.swing.GroupLayout ind_7Layout = new javax.swing.GroupLayout(ind_7);
        ind_7.setLayout(ind_7Layout);
        ind_7Layout.setHorizontalGroup(
            ind_7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 3, Short.MAX_VALUE)
        );
        ind_7Layout.setVerticalGroup(
            ind_7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 42, Short.MAX_VALUE)
        );

        jLPedidos1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLPedidos1.setForeground(new java.awt.Color(255, 255, 255));
        jLPedidos1.setText("Pedidos");

        javax.swing.GroupLayout btnPanelPedidos1Layout = new javax.swing.GroupLayout(btnPanelPedidos1);
        btnPanelPedidos1.setLayout(btnPanelPedidos1Layout);
        btnPanelPedidos1Layout.setHorizontalGroup(
            btnPanelPedidos1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnPanelPedidos1Layout.createSequentialGroup()
                .addComponent(ind_7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLPedidos1)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        btnPanelPedidos1Layout.setVerticalGroup(
            btnPanelPedidos1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnPanelPedidos1Layout.createSequentialGroup()
                .addComponent(ind_7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(btnPanelPedidos1Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(jLPedidos1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        btnPanelPagamentos1.setBackground(new java.awt.Color(24, 34, 56));
        btnPanelPagamentos1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnPanelPagamentos1.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                btnPanelPedidos1MouseMoved(evt);
            }
        });
        btnPanelPagamentos1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnPanelPagamentos1MousePressed(evt);
            }
        });

        ind_8.setPreferredSize(new java.awt.Dimension(3, 42));

        javax.swing.GroupLayout ind_8Layout = new javax.swing.GroupLayout(ind_8);
        ind_8.setLayout(ind_8Layout);
        ind_8Layout.setHorizontalGroup(
            ind_8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 3, Short.MAX_VALUE)
        );
        ind_8Layout.setVerticalGroup(
            ind_8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 42, Short.MAX_VALUE)
        );

        jLPagamentos1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLPagamentos1.setForeground(new java.awt.Color(255, 255, 255));
        jLPagamentos1.setText("Pagamentos");

        javax.swing.GroupLayout btnPanelPagamentos1Layout = new javax.swing.GroupLayout(btnPanelPagamentos1);
        btnPanelPagamentos1.setLayout(btnPanelPagamentos1Layout);
        btnPanelPagamentos1Layout.setHorizontalGroup(
            btnPanelPagamentos1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnPanelPagamentos1Layout.createSequentialGroup()
                .addComponent(ind_8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLPagamentos1)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        btnPanelPagamentos1Layout.setVerticalGroup(
            btnPanelPagamentos1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnPanelPagamentos1Layout.createSequentialGroup()
                .addComponent(ind_8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addComponent(jLPagamentos1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        btnPanelCardapio1.setBackground(new java.awt.Color(24, 38, 69));
        btnPanelCardapio1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnPanelCardapio1.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                btnPanelPedidos1MouseMoved(evt);
            }
        });
        btnPanelCardapio1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnPanelCardapio1MousePressed(evt);
            }
        });

        ind_9.setPreferredSize(new java.awt.Dimension(3, 42));

        javax.swing.GroupLayout ind_9Layout = new javax.swing.GroupLayout(ind_9);
        ind_9.setLayout(ind_9Layout);
        ind_9Layout.setHorizontalGroup(
            ind_9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 3, Short.MAX_VALUE)
        );
        ind_9Layout.setVerticalGroup(
            ind_9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 42, Short.MAX_VALUE)
        );

        jLCardapio1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLCardapio1.setForeground(new java.awt.Color(255, 255, 255));
        jLCardapio1.setText("Cardápio");

        javax.swing.GroupLayout btnPanelCardapio1Layout = new javax.swing.GroupLayout(btnPanelCardapio1);
        btnPanelCardapio1.setLayout(btnPanelCardapio1Layout);
        btnPanelCardapio1Layout.setHorizontalGroup(
            btnPanelCardapio1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnPanelCardapio1Layout.createSequentialGroup()
                .addComponent(ind_9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLCardapio1)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        btnPanelCardapio1Layout.setVerticalGroup(
            btnPanelCardapio1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnPanelCardapio1Layout.createSequentialGroup()
                .addComponent(ind_9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(btnPanelCardapio1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLCardapio1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        btnPanelUsuarios1.setBackground(new java.awt.Color(24, 34, 56));
        btnPanelUsuarios1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnPanelUsuarios1.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                btnPanelPedidos1MouseMoved(evt);
            }
        });
        btnPanelUsuarios1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnPanelUsuarios1MousePressed(evt);
            }
        });
        btnPanelUsuarios1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                btnPanelUsuarios1KeyPressed(evt);
            }
        });

        ind_10.setPreferredSize(new java.awt.Dimension(3, 42));

        javax.swing.GroupLayout ind_10Layout = new javax.swing.GroupLayout(ind_10);
        ind_10.setLayout(ind_10Layout);
        ind_10Layout.setHorizontalGroup(
            ind_10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 3, Short.MAX_VALUE)
        );
        ind_10Layout.setVerticalGroup(
            ind_10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 42, Short.MAX_VALUE)
        );

        jLUsuarios1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLUsuarios1.setForeground(new java.awt.Color(255, 255, 255));
        jLUsuarios1.setText("Usuários");

        javax.swing.GroupLayout btnPanelUsuarios1Layout = new javax.swing.GroupLayout(btnPanelUsuarios1);
        btnPanelUsuarios1.setLayout(btnPanelUsuarios1Layout);
        btnPanelUsuarios1Layout.setHorizontalGroup(
            btnPanelUsuarios1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnPanelUsuarios1Layout.createSequentialGroup()
                .addComponent(ind_10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLUsuarios1)
                .addGap(0, 66, Short.MAX_VALUE))
        );
        btnPanelUsuarios1Layout.setVerticalGroup(
            btnPanelUsuarios1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnPanelUsuarios1Layout.createSequentialGroup()
                .addComponent(ind_10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addComponent(jLUsuarios1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jLabel16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/legourmet/imgs/icons8_About_18px.png"))); // NOI18N
        jLabel16.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/legourmet/imgs/icons8_Info_18px.png"))); // NOI18N
        jLabel10.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/legourmet/imgs/icons8_Help_18px.png"))); // NOI18N
        jLabel11.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnPanelPedidos1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(btnPanelPagamentos1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(btnPanelCardapio1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(btnPanelUsuarios1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel16)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel10)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel11))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(45, 45, 45)
                        .addComponent(jLabel3)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLNomeUsuario1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jTFPerfil1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLNomeUsuario1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTFPerfil1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(52, 52, 52)
                .addComponent(btnPanelPedidos1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(btnPanelPagamentos1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(btnPanelCardapio1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(btnPanelUsuarios1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 375, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jLabel16)
                    .addComponent(jLabel10)
                    .addComponent(jLabel11))
                .addGap(19, 19, 19))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 140, 770));

        jPanel2.setBackground(new java.awt.Color(239, 152, 43));
        jPanel2.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                jPanel2MouseDragged(evt);
            }
        });
        jPanel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jPanel2MousePressed(evt);
            }
        });

        btnDeslogar1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/legourmet/imgs/icons8_Exit_25px.png"))); // NOI18N
        btnDeslogar1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnDeslogar1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnDeslogar1MousePressed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(1195, Short.MAX_VALUE)
                .addComponent(btnDeslogar1)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnDeslogar1, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 0, 1230, 40));

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/legourmet/imgs/logo350px.png"))); // NOI18N

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(439, 439, 439)
                .addComponent(jLabel2)
                .addContainerGap(441, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(216, 216, 216)
                .addComponent(jLabel2)
                .addContainerGap(255, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 40, 1230, 730));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    // Abre FormPedidos
    private void btnPanelPedidos1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnPanelPedidos1MousePressed
        FormPedidos janela = new FormPedidos();
        //this.setEnabled(false);
        janela.setVisible(true);

//        Teste janela = new Teste();
//        janela.setVisible(true);


        //setColor(btn_7);
        //ind_7.setOpaque(true); //palitinho branco ao lado esquerdo do button
        // deixa os botões e indicadores sem destaque
        //resetColor(new JPanel[]{btn_8, btn_9, btn_10}, new JPanel[]{ind_8, ind_9, 10});
        //        resetColor(btn_4);
        //        resetColor(btn_5);
        //        resetColor(btn_6);
    }//GEN-LAST:event_btnPanelPedidos1MousePressed

    // Abre FormPagamentos
    private void btnPanelPagamentos1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnPanelPagamentos1MousePressed
        FormPagamentosOld janela = new FormPagamentosOld();
        janela.setVisible(true);
        //setColor(btn_8);

        //ind_8.setOpaque(true); //palitinho branco ao lado esquerdo do button
        // deixa os botões e indicadores sem destaque
        //resetColor(new JPanel[]{btn_7, btn_9, btn_10}, new JPanel[]{ind_7, ind_9, ind_10});
    }//GEN-LAST:event_btnPanelPagamentos1MousePressed

    // Abre FormCardápio
    private void btnPanelCardapio1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnPanelCardapio1MousePressed
        FormCardapio janela = new FormCardapio();
        //this.setEnabled(false);
        janela.setVisible(true);
        //setColor(btn_9);

        //ind_9.setOpaque(true); //palitinho branco ao lado esquerdo do button
        // deixa os botões e indicadores sem destaque
        //resetColor(new JPanel[]{btn_7, btn_8, btn_10}, new JPanel[]{ind_7, ind_8, ind_10});
    }//GEN-LAST:event_btnPanelCardapio1MousePressed

    // Abre FormUsuarios
    private void btnPanelUsuarios1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnPanelUsuarios1MousePressed
        FormUsuarios janela = new FormUsuarios();
        //this.setEnabled(false);
        janela.setVisible(true);

        // setColor(btn_10);
        //ind_10.setOpaque(true); //palitinho branco ao lado esquerdo do button
        // deixa os botões e indicadores sem destaque
        // resetColor(new JPanel[]{btn_7, btn_8, btn_9}, new JPanel[]{ind_7, ind_8, ind_9});
    }//GEN-LAST:event_btnPanelUsuarios1MousePressed

    // Encerrar do sistema
    private void btnDeslogar1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnDeslogar1MousePressed
        int resposta = JOptionPane.showConfirmDialog(null, "Deseja realmente sair?", "Sair", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);
        if (resposta == JOptionPane.YES_OPTION) {
            System.exit(0);
        }
    }//GEN-LAST:event_btnDeslogar1MousePressed

    private void btnPanelUsuarios1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_btnPanelUsuarios1KeyPressed
        
    }//GEN-LAST:event_btnPanelUsuarios1KeyPressed

    private void btnPanelPedidos1MouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnPanelPedidos1MouseMoved
        
    }//GEN-LAST:event_btnPanelPedidos1MouseMoved

    // Métodos jPanel2MouseDragged e jPanel2MousePressed são para mover a tela
    private void jPanel2MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel2MouseDragged
        // src to drag
        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();
        this.setLocation(x-xx, y-xy);
    }//GEN-LAST:event_jPanel2MouseDragged

    int xx, xy;
    private void jPanel2MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel2MousePressed
        // drag this pane
        xx = evt.getX();
        xy = evt.getY();
    }//GEN-LAST:event_jPanel2MousePressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel btnDeslogar1;
    private javax.swing.JPanel btnPanelCardapio1;
    private javax.swing.JPanel btnPanelPagamentos1;
    private javax.swing.JPanel btnPanelPedidos1;
    private javax.swing.JPanel btnPanelUsuarios1;
    private javax.swing.JPanel ind_10;
    private javax.swing.JPanel ind_7;
    private javax.swing.JPanel ind_8;
    private javax.swing.JPanel ind_9;
    private javax.swing.JLabel jLCardapio1;
    private javax.swing.JLabel jLNomeUsuario1;
    private javax.swing.JLabel jLPagamentos1;
    private javax.swing.JLabel jLPedidos1;
    private javax.swing.JLabel jLUsuarios1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JTextField jTFPerfil1;
    // End of variables declaration//GEN-END:variables
}
